import type { NextPage } from "next";
import Head from "next/head";
import { Body3, Title2 } from "~/constants/Typography";

import * as Styled from "../styles/index.style";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next asdadas</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Styled.Container>
      <Styled.Inner>
        <Body3>boilerplate</Body3>
        <Title2>하이</Title2>
      </Styled.Inner>
    </Styled.Container>
  </div>
);

export default Home;
